[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/contact"
  to = "/"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
