backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

site_url: https://krauss-cms.netlify.app
logo_url: https://chlzslvdr.sirv.com/krauss/logo.png
media_folder: static/assets
public_folder: /assets

collections:
  - name: "pages"
    label: "Krauss CMS"
    files:
      - name: "home"
        label: "Home"
        file: "src/contents/home.md"
        format: "frontmatter"
        preview_path: "/"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - label: "Navigations"
            name: "navigations"
            widget: list
            max: 5
            add_to_top: true
            minimize_collapsed: true
            fields:
              - { label: "Page", name: "page", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - {
                  label: "Show Navigation",
                  name: "is_show",
                  widget: "boolean",
                  default: true,
                }
          - label: "Social Links"
            name: "social_links"
            widget: list
            max: 5
            add_to_top: true
            minimize_collapsed: true
            fields:
              - { label: "Platform", name: "platform", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Icon", name: "icon_class", widget: "string" }
              - {
                  label: "Show Social Link",
                  name: "is_show",
                  widget: "boolean",
                  default: true,
                }

      - name: "about"
        label: "About"
        file: "src/contents/about.md"
        format: "frontmatter"
        preview_path: "/about"
        fields:
          - label: "Summary"
            name: "summary"
            widget: "object"
            fields:
              - { label: "Job Title", name: "job_title", widget: "string" }
              - { label: "Phone", name: "phone", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "About Me", name: "about", widget: "string" }

          - label: "Technology Stacks"
            name: "technology_stacks"
            widget: "list"
            add_to_top: true
            minimize_collapsed: true
            fields:
              - { label: "Technology", name: "tech", widget: "string" }
              - { label: "Icon", name: "icon_class", widget: "string" }
              - {
                  label: "Data Icon",
                  name: "data_icon",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Show Technology Stack",
                  name: "is_show",
                  widget: "boolean",
                  default: true,
                }

          - label: "Certificates"
            name: "certificates"
            widget: "list"
            add_to_top: true
            minimize_collapsed: true
            fields:
              - { label: "Course", name: "course", widget: "string" }
              - { label: "Url", name: "url", widget: "string" }
              - { label: "Icon", name: "icon_class", widget: "string" }
              - {
                  label: "Data Icon",
                  name: "data_icon",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Show Certificate",
                  name: "is_show",
                  widget: "boolean",
                  default: true,
                }

      - name: "resume"
        label: "Resume"
        file: "src/contents/resume.md"
        format: "frontmatter"
        preview_path: "/resume"
        fields:
          - label: "Personal Info"
            name: "personal_info"
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Address", name: "address", widget: "string" }
              - { label: "Phone", name: "phone", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "Summary", name: "summary", widget: "string" }

          - label: "Educations"
            name: "educations"
            widget: "list"
            add_to_top: true
            minimize_collapsed: true
            fields:
              - { label: "School", name: "school", widget: "string" }
              - { label: "Degree", name: "degree", widget: "string" }
              - {
                  label: "Year Started",
                  name: "year_started",
                  widget: "number",
                }
              - {
                  label: "Year Ended",
                  name: "year_ended",
                  widget: "number",
                  required: false,
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Show Education",
                  name: "is_show",
                  widget: "boolean",
                  default: true,
                }

          - label: "Professional Experiences"
            name: "professional_experiences"
            widget: "list"
            add_to_top: true
            minimize_collapsed: true
            fields:
              - { label: "Company", name: "company", widget: "string" }
              - { label: "Position", name: "position", widget: "string" }
              - { label: "Start Date", name: "start_date", widget: "string" }
              - {
                  label: "End Date",
                  name: "end_date",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                  required: false,
                }
              - {
                  label: "Show Experience",
                  name: "is_show",
                  widget: "boolean",
                  default: true,
                }

          - label: "Upload Resume"
            name: "cv"
            widget: "file"
            accept: ".pdf"
            allow_multiple: false
            required: false

      - name: "portfolio"
        label: "Portfolio"
        file: "src/contents/portfolio.md"
        format: "frontmatter"
        preview_path: "/portfolio"
        fields:
          - label: "Projects"
            name: "projects"
            widget: list
            add_to_top: true
            minimize_collapsed: true
            fields:
              - {
                  label: "Project Name",
                  name: "project_name",
                  widget: "string",
                }
              - { label: "Url", name: "url", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - {
                  label: "Show Project",
                  name: "is_show",
                  widget: "boolean",
                  default: true,
                }

      - name: "testimonials"
        label: "Testimonials"
        file: "src/contents/testimonials.md"
        format: "frontmatter"
        preview_path: "/about"
        fields:
          - label: "Testimonials"
            name: "testimonials"
            widget: list
            add_to_top: true
            minimize_collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Company",
                  name: "company",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Testimonial",
                  name: "testimonial",
                  widget: "text",
                  pattern: ["^.{1,500}$", "Max 500 characters."],
                }
              - {
                  label: "Show Testimonial",
                  name: "is_show",
                  widget: "boolean",
                  default: true,
                }

  - name: "blog"
    label: "Blog"
    folder: "src/contents/blog"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    identifier_field: "title"
    preview_path: "/blog/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "LL" }
      - {
          label: "Author",
          name: "author",
          widget: "string",
          default: "Tabitha Krauss",
        }
      - {
          label: "Featured Image",
          name: "featured_image",
          widget: "image",
          required: false,
        }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Content", name: "body", widget: "markdown" }
      - {
          label: "Show Blog",
          name: "is_show",
          widget: "boolean",
          default: true,
        }
